# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-20 15:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(default='Marion', max_length=100)),
                ('conjoint', models.CharField(blank=True, default='Hugo', max_length=100)),
                ('enfants', models.BooleanField()),
                ('adresse', models.TextField(default='Pau', null=True)),
            ],
        ),
    ]
