# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-20 20:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('conjoint', models.CharField(blank=True, max_length=100)),
                ('enfants', models.BooleanField()),
                ('adresse', models.TextField(null=True)),
                ('vientSure', models.BooleanField()),
                ('vientPeut_etre', models.BooleanField()),
                ('vientPas', models.BooleanField()),
            ],
        ),
    ]
