# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-20 15:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='adresse',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='guest',
            name='conjoint',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='guest',
            name='nom',
            field=models.CharField(max_length=100),
        ),
    ]
